name: Deploy Application to Server

on:
  push:
    branches:
      - main  # Pas dit aan naar de branch die je wilt deployen (bijv. 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specificeer het platform voor de job

    steps:
      # Checkout de repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Voeg SSH privé sleutel toe via GitHub secrets
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Voer de deploy uit via SSH
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@130.162.242.76 << 'EOF'
            # Voeg hier je deploy commando's toe, bijvoorbeeld:
            cd /path/to/your/application
            git pull origin main  # Verondersteld dat je code via Git komt
            # Voeg hier andere deploytaken toe, zoals het restart van een service:
            sudo systemctl restart your-app-service
          EOF
